# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushover < Formula
  desc "Unofficial command-line client for the Pushover Message API"
  homepage "https://github.com/jurgenj136/pushover-cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.2/pushover_0.1.2_darwin_amd64.tar.gz"
      sha256 "17179d4bb581246bdf6bb89e94d30fea99fb2a1d1e453856f2ab4864cc1a1a2c"

      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.2/pushover_0.1.2_darwin_arm64.tar.gz"
      sha256 "a8b6c451b398d0f95767a9248371e7c847205a296900084235edc9b28e9b7f26"

      define_method(:install) do
        bin.install "pushover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.2/pushover_0.1.2_linux_amd64.tar.gz"
      sha256 "534f69507367b2429aebec2c548a926fa74f8cb4782c0257f60f33929d2c6554"
      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.2/pushover_0.1.2_linux_arm64.tar.gz"
      sha256 "43ca990f4a4419964a9a02cf3062fe8db0004532457c0172cb4b4ad80baf5b95"
      define_method(:install) do
        bin.install "pushover"
      end
    end
  end
end
