# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushover < Formula
  desc "Unofficial command-line client for the Pushover Message API"
  homepage "https://github.com/jurgenj136/pushover-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.1/pushover_0.1.1_darwin_amd64.tar.gz"
      sha256 "8518220350818694e4c4bbfaf91166a3afb8222e70f479a2d54ac3ad8719887b"

      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.1/pushover_0.1.1_darwin_arm64.tar.gz"
      sha256 "2949ada0a1b93f3ba10718c462f90bb97019867a18ab7e357d6b599d7dab8a2d"

      define_method(:install) do
        bin.install "pushover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.1/pushover_0.1.1_linux_amd64.tar.gz"
      sha256 "e8fb1fe52a277aa9c89070e50d35dfc5d73a3ae7af56a2113375fd068dd2fec2"
      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.1/pushover_0.1.1_linux_arm64.tar.gz"
      sha256 "bfd2226f28fdc4cb98571aff555c78798ee42cc5c815201e3eff3858619a3ab8"
      define_method(:install) do
        bin.install "pushover"
      end
    end
  end
end
