# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushover < Formula
  desc "Unofficial command-line client for the Pushover Message API"
  homepage "https://github.com/jurgenj136/pushover-cli"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.3/pushover_0.1.3_darwin_amd64.tar.gz"
      sha256 "992800a3d1f153a6d3bf3d9b8c992736a73b531ef4a126eb0004f3edd37b1b58"

      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.3/pushover_0.1.3_darwin_arm64.tar.gz"
      sha256 "3f71bd88c1c62cd49f65a48f78c24a33e7f700ae2303b0a9979174ba21478be5"

      define_method(:install) do
        bin.install "pushover"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.3/pushover_0.1.3_linux_amd64.tar.gz"
      sha256 "97b4716ff481489d79681c5c3089b2c42cf477db03fdcc7bb2c105639297ac9a"
      define_method(:install) do
        bin.install "pushover"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jurgenj136/pushover-cli/releases/download/v0.1.3/pushover_0.1.3_linux_arm64.tar.gz"
      sha256 "b748f3ae5bce3df34793c1c8b53f4cd4632670cd59f544f358b140233838ae02"
      define_method(:install) do
        bin.install "pushover"
      end
    end
  end

  test do
    system "#{bin}/pushover", "--json", "version"
  end
end
